### ISSUE TITLE
Nullpointerexception on clicking items

### ISSUE THREAD

**Issue by barpec12** [hammy2899/ArchonCrates#10]
When I'm clicking on items, that aren't keys I get this error.
`[21:13:51] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ArchonCrates v19.1.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1023) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched.jar:git-TacoSpigot-"1a0d11cc"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched.jar:git-TacoSpigot-"1a0d11cc"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched.jar:git-TacoSpigot-"1a0d11cc"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched.jar:git-TacoSpigot-"1a0d11cc"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched.jar:git-TacoSpigot-"1a0d11cc"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at com.HamiStudios.ArchonCrates.Events.PlayerInteraction.OnInteraction(PlayerInteraction.java:43) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor321.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched.jar:git-TacoSpigot-"1a0d11cc"]
	... 19 more`

**Comment by y0hami** [comment]
Hi, barpec12

Is this when your in the give key menu?

**Comment by barpec12** [comment]
Hi, Hammy2899
No, it is showing, when I try, for example place a block (with closed
inventory, can't place blocks with opened inventory xd).

**Comment by y0hami** [comment]
Can you give me a snippet of your key config file, I think it may be something in there. I am also going to do some testing around the interaction events when I get a chance.
