### ISSUE TITLE
Update error in console

### ISSUE THREAD

**Issue by CyrusMusic101** [hammy2899/ArchonCrates#27]
When I join the server in console it throws out this:

[16:11:43 INFO]: UUID of player OctoberTroy is 5bce7a23-c226-4df5-80b8-b56e46b50a96
[16:11:43 WARN]: java.lang.NullPointerException
[16:11:43 WARN]:        at com.HamiStudios.ArchonCrates.Util.UpdateChecker.needsUpdated(UpdateChecker.java:36)
[16:11:43 WARN]:        at com.HamiStudios.ArchonCrates.Events.OnJoin.onJoin(OnJoin.java:36)
[16:11:43 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:11:43 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:11:43 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:11:43 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[16:11:43 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[16:11:43 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:11:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:11:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:11:43 WARN]:        at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:272)
[16:11:43 WARN]:        at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156)
[16:11:43 WARN]:        at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[16:11:44 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:11:44 WARN]: java.lang.NullPointerException
[16:11:44 WARN]:        at com.HamiStudios.ArchonCrates.Util.UpdateChecker.needsUpdated(UpdateChecker.java:36)
[16:11:44 WARN]:        at com.HamiStudios.ArchonCrates.Events.OnJoin.onJoin(OnJoin.java:42)
[16:11:44 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:11:44 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:11:44 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:11:44 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[16:11:44 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[16:11:44 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:11:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:11:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:272)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[16:11:44 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[16:11:44 WARN]:        at java.lang.Thread.run(Unknown Source)

or when command is run:

[16:15:23 INFO]: OctoberTroy issued server command: /archoncrates update
[16:15:24 WARN]: java.lang.NullPointerException
[16:15:24 WARN]:        at com.HamiStudios.ArchonCrates.Util.UpdateChecker.needsUpdated(UpdateChecker.java:36)
[16:15:24 WARN]:        at com.HamiStudios.ArchonCrates.Commands.CheckUpdates.run(CheckUpdates.java:22)
[16:15:24 WARN]:        at com.HamiStudios.ArchonCrates.Commands.Commands.onCommand(Commands.java:109)
[16:15:24 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:15:24 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:15:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[16:15:24 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:15:24 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[16:15:24 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:15:24 WARN]: java.lang.NullPointerException
[16:15:24 WARN]:        at com.HamiStudios.ArchonCrates.Util.UpdateChecker.needsUpdated(UpdateChecker.java:36)
[16:15:24 WARN]:        at com.HamiStudios.ArchonCrates.Commands.CheckUpdates.run(CheckUpdates.java:28)
[16:15:24 WARN]:        at com.HamiStudios.ArchonCrates.Commands.Commands.onCommand(Commands.java:109)
[16:15:24 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:15:24 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:15:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[16:15:24 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:15:24 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[16:15:24 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[16:15:24 WARN]:        at java.lang.Thread.run(Unknown Source)

Yes im using the latest version of archoncrates.

**Comment by y0hami** [comment]
Are you sure you're using the latest version?

**Comment by CyrusMusic101** [comment]
Yes, could it be because I'm using the 1.8 version since I have a 1.8 server?

**Comment by y0hami** [comment]
Are you using [v17.3](https://dev.bukkit.org/projects/archoncrates/files/906197)
