### ISSUE TITLE
Cannot close Crate GUI

### ISSUE THREAD

**Issue by SKILLSHOTZZZ** [hammy2899/ArchonCrates#28]
I cannot close the Crates GUI whenever I use a key on the crate.

Version of Server: v1.11.2+
Server Type: Spigot

Here is the error I get:

[13:04:15 WARN]: [ArchonCrates] Task #1794 for ArchonCrates v19.1.3 generated an exception
java.lang.IndexOutOfBoundsException: No group 5
	at java.util.regex.Matcher.start(Matcher.java:375) ~[?:1.8.0_172]
	at java.util.regex.Matcher.appendReplacement(Matcher.java:880) ~[?:1.8.0_172]
	at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_172]
	at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_172]
	at com.HamiStudios.ArchonCrates.API.Operations.CrateRoll.generateWinningPrize(CrateRoll.java:545) ~[?:?]
	at com.HamiStudios.ArchonCrates.API.Operations.CrateRoll.access$500(CrateRoll.java:22) ~[?:?]
	at com.HamiStudios.ArchonCrates.API.Operations.CrateRoll$3.run(CrateRoll.java:240) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

**Comment by SKILLSHOTZZZ** [comment]
@hammy2899

**Comment by SKILLSHOTZZZ** [comment]
Nvm, found the error and fixed already

**Comment by WolfGameStudios** [comment]
@SKILLSHOTZZZ can you tell me what you did to fix this error? I am facing the same issue.

@hammy2899 I'd advise creating a better documentation that fully explains everything rather than letting us fend for ourselves most of the time.

**Comment by boopdev** [comment]
@SKILLSHOTZZZ pls tell secrets, i have the same issue, i need help. xoxo
